### ISSUE TITLE
Provide an "official" torrent link for the disk image

### ISSUE THREAD

**Issue by brad** [jasperproject/jasperproject.github.io#18]
It's a large file, and that way we can save sourceforge the bandwidth. I found this torrent:

http://burnbit.com/torrent/290881/jasper_disk_image_tar_gz

which seems totally legit, but I'd feel better about it if I knew the project owners had signed off on it.

**Comment by EMCP** [comment]
I second this.. seeing a dead link for the RPi 2 precompiled image hosted on GDrive is unencouraging

**Comment by NeilHendrick** [comment]
Yes, please. It's tricky just to find and download the disk image. This needs to be consolidated in the Jasper support pages.

**Comment by mattcurrycom** [comment]
There is a link on the main page of the forums....

**Comment by mattcurrycom** [comment]
I agree, put in a PR...
