### ISSUE TITLE
Unnecessary reference to Debian Sid/Jessie

### ISSUE THREAD

**Issue by jrlandau** [jasperproject/jasperproject.github.io#34]
Many users, especially beginners, will have arrived at this reference (in the Install Guide) by Method 1.  In this case, they are using whatever version of Debian was provided in the image file, and they won't know which.  So this condition is simply confusing.

**Comment by shbhrsaha** [comment]
Hi Joe-- I understand what you're saying, but Method 1 followers will actually never need to follow [Install Dependencies for PocketSphinx STT engine](http://jasperproject.github.io/documentation/installation/#installing-sphinx), the section mentioning Debian versions. After downloading the disk image, they are asked to jump to [Configuration](http://jasperproject.github.io/documentation/configuration/).

**Comment by jrlandau** [comment]
Hi Shbhrsaha
Maybe I'm missing something--the Method 1 instructions say, 
"After imaging your SD card, clone the repository and install the Python dependencies as described in Install Jasper. Then, skip to Configuration."
Installing the Python dependencies leads to the paragraph that confused me.

**Comment by jrlandau** [comment]
Shbhrsaha <https://github.com/shbhrsaha>, (will this reach you?) please see
my comment under issue # 34.


*Joe*

**Comment by jrlandau** [comment]
My suggestion would be, under Method 1 (near the top of the page), change
the sentences

 "After imaging your SD card, clone the repository and install the Python
dependencies as described in Install Jasper
<http://jasperproject.github.io/documentation/installation/#install-jasper>.
Then, skip to Configuration
<http://jasperproject.github.io/documentation/configuration/>."

to read

"After imaging your SD card, go directly to Configuration
<http://jasperproject.github.io/documentation/configuration/>."

I am assuming here that all the dependencies are already in the Method 1
disk image, not just the Pocketsphinx ones.  Is this the case?

**Comment by shbhrsaha** [comment]
The dependencies are on the disk image, but the client code prescribed in the 'Install Jasper' section is not. So, I'm afraid we can't remove the 'Install Jasper' recommendation altogether
