### ISSUE TITLE
Phonetisaurus source download fails with a 404

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [jasperproject/jasperproject.github.io#45]
In the steps listed for building the dependencies for pocketsphinx from scratch, the wget for the phonetisaurus source is failing with a 404. Is there a newer version of the phonetisaurus source that can be used?

![2015-08-14-150222_1024x768_scrot](https://cloud.githubusercontent.com/assets/6392604/9281789/a1ff0e0a-4295-11e5-91d9-23c4bb1900e3.png)

**Comment by ashubhatt** [comment]
Use this file instead:

https://code.google.com/p/phonetisaurus/downloads/detail?name=is2013-conversion.tgz

**Comment by Moini** [comment]
The file from the comment by @ashubhatt doesn't exist any more.

**Comment by Moini** [comment]
A solution is described here:
https://github.com/jasperproject/jasper-client/issues/436

Could the instructions on the website be updated?

**Comment by ashubhatt** [comment]
@Moini I think you should recheck. The file is still available from that same link.
Otherwise you can check: https://code.google.com/archive/p/phonetisaurus/downloads
and download **is2013-conversion.tgz**

**Comment by Moini** [comment]
Yes, you're right. The error had to do with my noscript. I've been activating javascripts one by one, and that somehow broke the page. It works when I re-enter the link after allowing all necessary javascripts.

**Comment by Holzhaus** [comment]
This has been fixed via jasperproject.github.io#60. Closing this.
