### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pcs3rd** [jasperproject/jasperproject.github.io#59]
When I try to get pip, it all fails when trying 2 install manually. Is there an image you guys could upload already in the squashfs format for berryboot?

**Comment by GeoBeBee** [comment]
I fell over the PIP problem, and fixed it, see my sequence here:
[https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt](https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt)
