### ISSUE TITLE
Armv6h stt install (arch)

### ISSUE THREAD

**Issue by stevenwalton** [jasperproject/jasperproject.github.io#65]
So I have a fresh build of arch on the rpi2 and trying to build pocketsphinx (or any stt for that matter). I keep hitting an error for the dependency `cmuclmtk` and `m2m-aligner` that is needed under the package build for [pocketsphinx](https://aur.archlinux.org/packages/jasper-stt-pocketsphinx/), and all the other stt engines through the AUR, saying it doesn't support armv6h. I even tried just building sphinx and ran into this problem. The website suggests that Jasper was built for use with the pi but I keep running into arm errors. Is there another suggested stt engine that I can use without this dependency? Or another way to build?

I installed arch with [these instructions](https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2)

**Comment by Holzhaus** [comment]
http://raspberrypi.stackexchange.com/questions/5412/how-to-automagically-have-yaourt-makepkg-add-the-armv6h-platform-to-pkgbuild
